services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: pokedex-dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
    ports:
      - '8000:8000'
    networks:
      - pokedex-local

networks:
  pokedex-local:
    name: pokedex-local
